name: utr3.venv
channels:
  - bioconda
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - bzip2=1.0.8=h500dc9f_8
  - c-ares=1.34.6=hb5e19a0_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - debugpy=1.8.19=py312h6c02384_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - htslib=1.23=h9f635df_0
  - icu=78.2=h14c5de8_0
  - igvtools=2.17.3=hdfd78af_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.9.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h37d8d59_0
  - libblas=3.11.0=5_he492b99_openblas
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libcurl=8.18.0=h9348e2b_0
  - libcxx=21.1.8=h3d58e20_0
  - libdeflate=1.22=h00291cd_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libexpat=2.7.3=heffb93a_0
  - libffi=3.5.2=h750e83c_0
  - libgcc=15.2.0=h08519bb_15
  - libgfortran=15.2.0=h7e5c614_15
  - libgfortran5=15.2.0=hd16e46c_15
  - libiconv=1.18=h57a12c2_2
  - libidn2=2.3.8=h13f126c_1
  - libintl=0.25.1=h3184127_1
  - liblapack=3.11.0=5_h859234e_openblas
  - liblzma=5.8.1=hd471939_2
  - libnghttp2=1.67.0=h3338091_0
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.51.1=hd09e2f1_1
  - libssh2=1.11.1=hed3591d_0
  - libunistring=0.9.10=h0d85af4_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.8=h472b3d1_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - narwhals=2.15.0=pyhcf101f3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.4.1=py312hb34da66_0
  - openjdk=25.0.1=h2014cc5_0
  - openssl=3.6.0=h230baf5_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312h86abcb1_2
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.45=hf733adb_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - plotly=6.5.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py312hf7082af_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.12=h74c2667_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py312hb7d603e_0
  - readline=8.3=h68b038d_0
  - referencing=0.37.0=pyhcf101f3_0
  - rpds-py=0.30.0=py312h8a6388b_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tabix=1.11=hdfd78af_0
  - tk=8.6.13=hf689a15_3
  - tornado=6.5.4=py312h404bc50_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wget=1.25.0=hfb6e5ea_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h6c33b1e_9
  - zlib=1.3.1=hd23fc13_2
  - zstd=1.5.7=h3eecb57_6
  - pip:
      - natsort==8.4.0
      - pyranges1==1.1.8
      - ruranges==0.0.15
      - tabulate==0.9.0
prefix: /Users/andrejnekrasov/mambaforge/envs/utr3.venv
