name: utr3.venv
channels:
  - bioconda
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - bzip2=1.0.8=h500dc9f_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h14c5de8_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - libblas=3.11.0=5_he492b99_openblas
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libcxx=21.1.8=h3d58e20_0
  - libexpat=2.7.3=heffb93a_0
  - libffi=3.5.2=h750e83c_0
  - libgcc=15.2.0=h08519bb_15
  - libgfortran=15.2.0=h7e5c614_15
  - libgfortran5=15.2.0=hd16e46c_15
  - liblapack=3.11.0=5_h859234e_openblas
  - liblzma=5.8.1=hd471939_2
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libsqlite=3.51.1=hd09e2f1_1
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.8=h472b3d1_0
  - natsort=8.4.0=pyh29332c3_1
  - ncls=0.0.70=py312h73b7c68_0
  - ncurses=6.5=h0622a9a_3
  - numpy=2.4.1=py312hb34da66_0
  - openssl=3.6.0=h230baf5_0
  - pandas=2.3.3=py312h86abcb1_2
  - pip=25.3=pyh8b19718_0
  - pyranges=0.1.4=pyhdfd78af_0
  - python=3.12.12=h74c2667_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.3=h68b038d_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sorted_nearest=0.0.41=py312h73b7c68_0
  - tabulate=0.9.0=pyhcf101f3_3
  - tk=8.6.13=hf689a15_3
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
prefix: /Users/andrejnekrasov/mambaforge/envs/utr3.venv
